[package]
name = "litecraft"
version = "0.1.0-alpha"
authors = ["KernelFreeze <kernelfreeze@outlook.com>"]

[dependencies]
allegro = "0.0.32"
allegro_font = "0.0.32"
allegro_image = "0.0.32"
allegro_ttf = "0.0.32"
allegro-sys = "0.0.32"
allegro_audio = "0.0.32"
allegro_acodec = "0.0.32"
allegro_primitives = "0.0.32"
colored_logger = "0.1.0"
serde = "^1.0.8"
serde_derive = "^1.0.8"
log = "*"
clap = "2.27.1"
rand = "0.3.*"
os_type="1.0.0"
dirs = "0.3.1"
config = "0.7"
smallvec = "0.5.0"