[package]
name = "litecraft"
version = "0.1.0-alpha"
authors = ["KernelFreeze <kernelfreeze@outlook.com>"]

[dependencies]
allegro = "0.0.32"
allegro_font = "0.0.32"
allegro_image = "0.0.32"
badlog = "0.3.0"
log = "*"
clap = "2.27.1"
rand = "0.3.*"
os_type="1.0.0"
dirs = "0.3.1"