[package]
name = "Litecraft"
version = "0.1.1"
authors = ["Miguel Peláez <kernelfreeze@outlook.com>", "Raúl Salas <rauls.martin@alumno.sek.es>"]

[dependencies]
# Graphics
nalgebra = "0.12"
glfw = "0.12"

#Serde
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

log = "0.3"
env_logger = "0.3"
uuid = "0.3"
num-traits = "0.1"

byteorder = "1"
clap = "~2.19.0"

[dependencies.kiss3d]
git = "https://github.com/KernelFreeze/kiss3d"